name: quizz_app
description: "A Flutter quiz application with Clean Architecture"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/icons/
